version: '3.8'

services:
  postgres:
    container_name: scheduling_app_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: scheduling_app
    ports:
      - 5433:5432
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
